# RuboCop の設定ファイル（RuboCop のチェックの対象になるディレクトリ・ファイルの設定や Cop の有効無効の制御、Cop のカスタマイズ）
AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "config/initializers/devise.rb"
    - "config/environments/*.rb"
    - "Gemfile"
    - "Rakefile"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"

# メソッドの行数を 40 行まで許容
Metrics/MethodLength:
  Max: 40

# メソッドの複雑度
Metrics/AbcSize:
  Max: 40